title: "Vector.js"
blurb: Vector is an open source javascript library for creating interactive scalable vector graphics.
baseURL: "https://vectorjs.org"
languageCode: "en-us"
disableKinds: ["taxonomy", "taxonomyTerm"]
pygmentsUseClasses: true
publishDir: "../docs/"
staticDir:
  - static
  - ../api/
  - ../css/
  - ../dist/
  - ../resources/

params:
  repositoryURL: "https://github.com/vector-js/vector.git"

# Mount vectorjs library
module:
  mounts:
    - source: "node_modules/@vector-js/vector/dist/"
      target: "static/vector/"
    - source: "static"
      target: "static"

markup:
  goldmark:
    renderer:
      unsafe: true
